
const actionTypes = {
    UPDATE_SEARCH_TEXT: 'UPDATE_SEARCH_TEXT',
    UPDATE_INSTRUMENTS_TO_COMPARE: 'UPDATE_INSTRUMENTS_TO_COMPARE',
    UPDATE_SELECTED_INSTRUMENT: 'UPDATE_SELECTED_INSTRUMENT',
    UPDATE_SHOW_SEARCH_BAR: 'UPDATE_SEARCH_BAR'
}

export default actionTypes;